### ISSUE TITLE
Version 3.5 uses the SN30 Pro USB to connect the switch without a response

### ISSUE THREAD

**Issue by rainzzz** [zoggins/RetroSpy#101]
It is normal to connect using the pro handle, but the same way is used to connect using sn30pro, the host is not responding

**Comment by rainzzz** [comment]
The console is Nintendo switch

**Comment by rainzzz** [comment]
The version update log shows that the switch already supports sn30pro. Is the connection method different from the pro handle?

**Comment by rainzzz** [comment]
I checked the history log and I will try to hold down the Y key to connect.

**Comment by zoggins** [comment]
Yes, I need to update the wiki to include this information.  its on my
list. :)
