### ISSUE TITLE
Not registering fast inputs. (Genesis)

### ISSUE THREAD

**Issue by edru** [zoggins/RetroSpy#117]
When doing extremely fast inputs on Genesis, not all inputs are displayed even though the system is registering them.

**Comment by zoggins** [comment]
6 button or 3 button controller?

**Comment by edru** [comment]
Sorry for the late reply - this was tested with a 6 button controller, the user did not have a 3rd to test with.

You can watch his vods on twitch - https://twitch.tv/joeybaby69

WR record holder on all 3 sonic games, so he taps ABC really fast to spin dash and most of the time it only shows 1 or 2 buttons lighting up rather than all 3.

Possible he is just that fast though? Maybe the arduino isnt fast/powerful enough to catch it all.
