### ISSUE TITLE
MiSTer USB: time out on disconnect

### ISSUE THREAD

**Issue by edru** [zoggins/RetroSpy#127]
It seems if you kill the power to the mister before closing retrospy that it will hang waiting for the connection and not respond. You have to either right click the task on the taskbar, or in the task manager, and close it that way. 

Seems that it doesnt know how to handle losing the net connection to the mister.

**Comment by zoggins** [comment]
Cannot seem to repro this, it does take 15-30 seconds to register a disconnect, but it is detecting it and quitting the viewer.  I did find a bigger problem in that a disconnect and then a reconnect messes up the display output, which i fixed.
