### ISSUE TITLE
Solution for x86 Platforms

### ISSUE THREAD

**Issue by RetroWeeb** [zoggins/RetroSpy#35]
Evening zoggins,

I had someone come into my discord this evening trying to get RetroSpy to work in 32-bit/x86 windows. 

While x86 will build cleanly, it will fail with this error in Visual Studio (attached)
[FileNotFoundException.txt](https://github.com/zoggins/RetroSpy/files/2810722/FileNotFoundException.txt)

I attempted to use a version of the SlimDX library from one I was able to find from 2012 but experienced similar results. However, as a wild guess, removing this line for x86 works:

```   
void updateGamepadList()
{
            _vm.XIAndGamepad.UpdateContents(GamepadReader.GetDevices()); // <- This one
}
```
I had him verify that his inputs were working after I sent him a build. It would seem that this call isn't supported on x86 versions of SlimDX.dll. However, I don't claim to be a windows developer since my day job is UNIX development- just a gut feeling on the exception message.

It's also a bit concerning that the library is so old and completely non-existent (seems like their website is offline and git hub page abandoned). I don't have suggestions for a new library, but in the interim it would seem this would fix it so you can distribute x86 builds. 

Let me know if you would like a binary version of my build (though you could easily do it yourself).

Take it easy :)
- Anthony (RetroWeeb)

**Comment by zoggins** [comment]
That whole code path is for the display of PC controllers.  This is handy for PC games as well as using controllers on emulators.  I will try to figure out why the call is failing on 32 bit windows.

**Comment by zoggins** [comment]
What version of windows was this on?  8?

**Comment by RetroWeeb** [comment]
I saw this on Windows 10, he saw it on Windows 7. So if you test in 8, 7, or 10 you shouldn’t experience platform specific issues, hopefully...

**Comment by zoggins** [comment]
Best guess is that some dependency of SlimDX isn't installed with the 32-bit versions anymore.  I will attempt to figure out what it is.

**Comment by zoggins** [comment]
Even better.  SharpDX allows for AnyCPU, so now there are 3 executables for completeness.  1 that should work on both x64 and x86. and then an x64 and x86 specific exe.  Let me know if this solves the problem.  I set up a x86 Win 7 vm and it seems to work for me

**Comment by RetroWeeb** [comment]
I will check it out when I have time this evening, thanks for looking into this so quickly!

**Comment by RetroWeeb** [comment]
So I tested it in 32-bit windows 10 and it seems to be working, I'm gonna have the person in my discord check it out and report back.

**Comment by RetroWeeb** [comment]
So I haven't heard back from the individual on discord so I think this ticket can be closed. Thank you for looking into this and getting it fixed so quickly. You didn't have to, but you did it anyways. It's much appreciated. 

Take it easy.
