### ISSUE TITLE
[Feature Request] Sega Saturn Support

### ISSUE THREAD

**Issue by Shentokk** [zoggins/RetroSpy#6]
Are there any plans to add support for the Sega Saturn?

**Comment by zoggins** [comment]
I have preliminarily looked at it.  I should be possible, just a matter of getting time to do it.  The protocol isn't much different than the Genesis, but the only unknown is if the Arduino can keep up with the signals.

**Comment by Shentokk** [comment]
I see. Thank you for the reply. I hope something can be done in the future since most of my speedrunning is on the Saturn and I'd love to be able to document inputs for certain games.

**Comment by zoggins** [comment]
I will put it next on my list to attempt after I fix a bug with the playstation and turbo controllers.

**Comment by zoggins** [comment]
Done!
