### ISSUE TITLE
Saturn Mouse not detected as mouse by games in 3D Pad mode

### ISSUE THREAD

**Issue by Shentokk** [zoggins/RetroSpy#60]
I tried this with Policenauts to get mouse to be read. It would read the buttons just fine, but I could not get it to recognize mouse movement in the game or on the input reader. I tried with other mouse supported games like Virtua Cop 2 and Planet Joker with the same results.

I am using v2.9.1 release with the 3D pad jumper. 3D pad functions as normal, but mouse appears to not work.

**Comment by zoggins** [comment]
Will take a look

**Comment by zoggins** [comment]
Assuming you were using the mouse skin?

**Comment by zoggins** [comment]
The mouse didn't work in game either?  That is weird.  I am assuming it's the OEM mouse?

**Comment by zoggins** [comment]
Does it work on the Saturn dashboard, no did inserted?

**Comment by zoggins** [comment]
OEM Mouse.  Saturn Shuttle Mouse Skin. SATURN3D firmware.  Newest Firmware on the Uno, newest RetroSpy.  English translation of Policnauts, everything works fine for me.  Ummm, the newest firmware shouldn't matter, do you know what release the firmware is from or is it the newest?  Just curious, there shouldn't have been any changes that would affect the mouse.

**Comment by Shentokk** [comment]
The firmware was from the release package. Mouse is OEM model 1 (grey).

**Comment by zoggins** [comment]
And the buttons work, but not the movement!

**Comment by Shentokk** [comment]
That's correct.

**Comment by zoggins** [comment]
Still looking at this.  I cannot repro on my end.

**Comment by Shentokk** [comment]
Is there any technical information I can pull to help narrow it down?

**Comment by Shentokk** [comment]
Updated to v3.0 and mouse still doesn't seem to work. ABC & Start read properly, but the mouse portion doesn't function.

**Comment by Shentokk** [comment]
So I just wanted to update that it was an issue with the cable. Got a new one and now it works fine.

**Comment by zoggins** [comment]
Awesome!! Will close this issue.
