### ISSUE TITLE
Window size.

### ISSUE THREAD

**Issue by ZanasoBayncuh** [zoggins/RetroSpy#65]
The controller inputs preview window is massive and cannot be resized. Simply requesting the window be capable of being adjusted.

**Comment by zoggins** [comment]
It's on my list, trying to understand more of UI code at the moment.

**Comment by ZanasoBayncuh** [comment]
Aight cool man, thanks.

**Comment by zoggins** [comment]
I need to some more testing, but Pull Request is out for this.
https://github.com/zoggins/RetroSpy/pull/70
