### ISSUE TITLE
[Organization Request] Standardize system names for skins

### ISSUE THREAD

**Issue by edru** [zoggins/RetroSpy#78]
I notice some skins call the system by a name, NES, the company, SEGA, and even company/name.

Request to unify this across the board to either abbreviation (NES GEN GCN), or Company + Name.

**Comment by zoggins** [comment]
Are you using the newest version?  I did a cleanup and attempted to standardize the names in the newest release.

**Comment by edru** [comment]
i mean more in the skin design itself.

for example:
<skin name="Default" author="40wattrange" type="nes">
<skin name="Default" author="40wattRange" type="sega">

And I swore there was one that included the entire company and system like "Sega Dreamcast" - thought it wasnt dreamcast.

This is literally a small thing - i mainly discovered it since genesis was labeled sega, and not genesis, so was getting confused. This can basically just be ignored.

**Comment by zoggins** [comment]
The outlier was Genesis which was just labeled Sega.  I have changed it.
