### ISSUE TITLE
[Feature Request] Ability to hide systems in drop down

### ISSUE THREAD

**Issue by edru** [zoggins/RetroSpy#79]
One draw back of supporting so many systems is that the list grows ever longer. The ability to hide/show items would be nice.

or rather than a drop down menu, maybe a popup menu similar to a right click, that would list the company, then expand further into the systems of the company.

Similar to where you could right click on the desktop and expand the New or View menus.

**Comment by zoggins** [comment]
I will see what I can do. Thanks!
