### ISSUE TITLE
Recursive Lookup for Skin folder

### ISSUE THREAD

**Issue by edru** [zoggins/RetroSpy#85]
Ability to add sub-folders within skin folder to either group by system, or by collection.

Current behavior is that it expects all direct folders of skins to contain a skin.xml file.

would be nice to do something like 

/skins/Vector/NES
/skins/Vector/SNES
/skins/Photo/

and so on.

Stumbled on to this as I wanted to group all of my collection in one folder, and the default skins in another folder.

**Comment by zoggins** [comment]
This is a good idea!! Shouldn't be a problem either.

**Comment by zoggins** [comment]
Will be in the next release
