### ISSUE TITLE
[BUG] Settings lost if there is a bad skin

### ISSUE THREAD

**Issue by edru** [zoggins/RetroSpy#86]
If there is a folder in the skins folder without a .xml file or with a bad value declared (ie, calling for an image that doesnt exist), you will get the warning, but upon clicking OK and RS launching, all your settings are wiped back to default.

This includes Controller Source, COM port, as well as delay (delay being the real annoying one)

**Comment by edru** [comment]
Doing further testing it looks as if the com port and delay value is still intact, it just displays as null/0. It only changes value if you enter a new integer - so in this case its just the display that is bad.

**Comment by zoggins** [comment]
Will look into it. Thanks

**Comment by zoggins** [comment]
This will be fixed in the next release
